--- #YAML:1.0
name:                Remote-Use
version:             0.03
abstract:            Using modules from a remote server
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    File::Basename:                0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    Getopt::Long:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Programacion en paralelo 2 <pp2@>
